name: Mirror

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: TheTipsyTurtle/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:supes1100/circlici-test.git"
          destination-repo: "git@github.com:TheTipsyTurtle/test_circleCI.git"
      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v1
