name: Mirror to Bitbucket Repo

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: trying to get
        uses: ./.github/actions/git-mirror-action
          env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          with:
            source-repo: "git@github.com:supes1100/circlici-test.git"
            destination-repo: "git@github.com:TheTipsyTurtle/test_circleCI.git"
