name: Mirror

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: get fuking path
        run: pwd
      - name: entrypoint
        run: |
          set -e
          if [[ -n "$SSH_PRIVATE_KEY" ]]
          then
            mkdir -p /root/.ssh
            echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
            chmod 600 /root/.ssh/id_rsa
          fi
          mkdir -p ~/.ssh
          cp /root/.ssh/* ~/.ssh/ 2> /dev/null || true
          
      - name: git-mirror
        run: |
          set -e
          SOURCE_REPO=$1
          DESTINATION_REPO=$2
          GIT_SSH_COMMAND="ssh -v"
          echo "SOURCE=$SOURCE_REPO"
          echo "DESTINATION=$DESTINATION_REPO"
          git clone --mirror "$SOURCE_REPO" && cd `basename "$SOURCE_REPO"`
          git remote set-url --push origin "$DESTINATION_REPO"
          git fetch -p origin
          git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
          git push --mirror
