name: Mirror

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: entrypoint
        run: /entrypoint.sh
      - name: git-mirror
        run: /git-mirror.sh
