name: Mirror

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu:latest
    steps:
      - name: get fuking path
        uses: TheTipsyTurtle/git-mirror-action@v1.0.1
        with:
          source-repo: git@github.com:supes1100/circlici-test.git
          destination-repo: git@github.com:TheTipsyTurtle/test_circleCI.gi
